services:
  aidbox:
    image: 'healthsamurai/aidboxone:latest'
    depends_on:
      - aidbox-db
    links:
      - 'aidbox-db:database'
    ports:
      - '8888:8888'
    env_file:
      - .env.aidbox
      - .env
  aidbox-db:
    image: 'healthsamurai/aidboxdb:14.5'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devbox
  aidbox-healthcheck:
    image: curlimages/curl
    entrypoint: /bin/sleep 10000
    depends_on:
      - aidbox
    healthcheck:
      test: curl --fail http://aidbox:8888/__healthcheck || exit 1
      interval: 1s
      timeout: 20s
      retries: 100
  app:
    build: .
    env_file:
      - .env.app
      - .env
    depends_on:
      aidbox-healthcheck:
        condition: service_healthy